version: '3'
services:
  # client application 
  web:
    build: ./frontend
    expose:
      - ${CLIENT_PORT}
    environment:
      - CLIENT_PORT=${CLIENT_PORT}
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    links:
      - backend
    command: npm run start
  
  # server application 
  backend:
    build: ./backend
    expose:
      - ${SERVER_PORT}
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - NODE_ENV=${NODE_ENV}
      - DB_URI=${DB_URI}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    links:
      - db
    command: npm run dev

  db:
    image: mongo:latest
    ports:
      - 27017:27017

